### list and groupment of sources for Jet Energy Scales systematic shifts

data_analysis_2017 = {
    'CMS_scale_j_eta0to5_13Tev': ["SinglePionECAL",
                                  "SinglePionHCAL", 
                                  "AbsoluteFlavMap",
                                  "AbsoluteMPFBias", 
                                  "AbsoluteScale", 
                                  "AbsoluteStat", 
                                  "Fragmentation", 
                                  "FlavorQCD", 
                                  "TimePtEta", 
                                  "PileUpDataMC",
                                  "RelativeFSR",
                                  "RelativeStatFSR",
                                  "PileUpPtRef"],
    'CMS_scale_j_eta0to3_13TeV': ["PileUpPtEC1", 
                                  "PileUpPtEC2", 
                                  "PileUpPtBB", 
                                  "RelativeJEREC1", 
                                  "RelativeJEREC2", 
                                  "RelativePtEC1", 
                                  "RelativePtEC2", 
                                  "RelativeStatEC",
                                  "RelativePtBB"],
    'CMS_scale_j_eta3to5_13TeV': ["RelativeStatHF",
                                  "RelativePtHF", 
                                  "PileUpPtHF", 
                                  "RelativeJERHF"],
    'CMS_scale_j_RelativeBal_13TeV': ["RelativeBal"],
    'CMS_scale_j_RelativeSample_13TeV': ["RelativeSample"]
}
